# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'T_MVVM' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
pod 'Masonry'
pod 'KVOController'
pod 'MJRefresh'
  # Pods for T_MVVM

end
