# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Network_Demo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
pod 'AFNetworking'
pod 'YYCache'
  # Pods for Network_Demo

  target 'Network_DemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Network_DemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
