# Uncomment the next line to define a global platform for your project
 platform :ios, '8.0'
source 'git@gitlab.com:iosweyee/etspecremoterepo.git'
source 'https://github.com/CocoaPods/Specs.git'
target 'TestRepo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
#pod 'ETLeftAlignedLayout'
pod 'ETNeworkBase'
pod 'TestResources'
pod 'NVActivityIndicatorView'
pod 'PKHUD'
pod 'PullToRefreshKit'
pod 'SnapKit'
pod 'EmptyDataSet-Swift'

end
